### PR TITLE
improve async

### PR DESCRIPTION
**Pull request by ringabout**

### CODE REVIEW

**Comment by ringabout** [comment]
I think sometimes {.async.} is expensive.Maybe we should avoid it.
Look at this pr
https://github.com/dom96/jester/pull/236/files

**Comment by ThomasTJdev** [comment]
I like it with the `Futures`, but then my solution for checking, that a message is sent does not work, since only `async` supports `await`.

How should we then check, that the message has been sent?

```nim
proc publish*(ctx: MqttCtx, topic: string, message: string, qos=0, waitConfirmation = false): Future[void]=
  ## Publish a message

  let msgId = ctx.nextMsgId()
  ctx.workQueue[msgId] = Work(wk: PubWork, msgId: msgId, topic: topic, message: message, qos: qos)
  result = ctx.work()
  if waitConfirmation:
    while ctx.workQueue.len > 0 and hasKey(ctx.workQueue, msgId):
      await sleepAsync 1000 # Not working due to future
```

**Comment by ThomasTJdev** [comment]
The easy pick is just setting `publish()` to an `{.async.}`.

**Comment by ringabout** [comment]
I think that if it needs await, we should use {.async.}.If not, we can avoid use {.async.}.Must be asleep.Bye!

**Pull request closed without merging**
